version: "3.3"

services:
  33c8fea:
    build:
      context: ./besu/
    image: besu
    volumes:
      - ./besu/33c8fea/key:/key
      - ./besu/33c8fea/static-nodes.m4:/static-nodes.m4
      - ./besu/33c8fea/iptables.rules.sh:/iptables.rules.sh
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/key
      - BESU_NETWORK=dev
      - BESU_DISCOVERY_ENABLED=false
      - BESU_LOGGING=INFO
    cap_add:
      - NET_ADMIN

  client:
    build: 
      context: ./stunnel/
    image: stunnel
    environment:
      - CLIENT=yes
      - SERVICE=client
      - ACCEPT=0.0.0.0:4911
      - CONNECT=server:4912
    volumes:
      - ./stunnel/client.crt:/etc/stunnel/service.crt
      - ./stunnel/client.key:/etc/stunnel/service.key
    expose:
      - "4911"

  server:
    image: stunnel
    environment:
      - CLIENT=no
      - SERVICE=server
      - ACCEPT=0.0.0.0:4912
      - CONNECT=9ab5623:30303
    volumes:
      - ./stunnel/server.crt:/etc/stunnel/service.crt
      - ./stunnel/server.key:/etc/stunnel/service.key
    expose:
      - "4912"

  9ab5623:
    image: besu
    volumes:
      - ./besu/9ab5623/key:/key
      - ./besu/9ab5623/iptables.rules.sh:/iptables.rules.sh
    environment:
      - BESU_NODE_PRIVATE_KEY_FILE=/key
      - BESU_NETWORK=dev
      - BESU_DISCOVERY_ENABLED=false
      - BESU_LOGGING=OFF
      - BESU_MINER_ENABLED=true
      - BESU_MINER_COINBASE=0000000000000000000000000000000000000000
    expose:
      - "30303"
    cap_add:
      - NET_ADMIN
